# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

pod 'SIOSocket', '~> 0.2.0'
pod 'RestKit', '~> 0.20.0'

target 'WhiteboardiOS' do

end

target 'WhiteboardiOSTests' do

end

